macos_min_version:             # [osx and x86_64]
  - 10.15                      # [osx and x86_64]
c_stdlib_version:              # [osx and x86_64]
  - 10.15                      # [osx and x86_64]
imgui_variant:
  - default
  - docking