{% set name = "imgui" %}
{% set version = "1.91.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/ocornut/{{ name }}/archive/v{{ version }}.tar.gz
    sha256: c5fbc5dcab1d46064001c3b84d7a88812985cde7e0e9ced03f5677bec1ba502a
  - path: CMakeLists.txt
  - path: imgui-config.cmake.in

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('imgui', max_pin='x.x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - cmake
    - ninja
  host:
    - libgl-devel  # [linux]
    - glfw
    - sdl2

test:
  files:
    - test/
  requires:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make  # [not win]
    - ninja  # [win]
  commands:
    - test -f $PREFIX/lib/libimgui${SHLIB_EXT}  # [unix]
    - if not exist %LIBRARY_PREFIX%\lib\imgui.lib exit 1  # [win]
    - if not exist %LIBRARY_PREFIX%\bin\imgui.dll exit 1  # [win]

about:
  home: https://github.com/ocornut/imgui
  summary: ImGui is a bloat-free graphical user interface library for C++. It outputs optimized vertex buffers that you can render anytime in your 3D-pipeline-enabled application.
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - Tobias-Fischer
    - traversaro
