{% set name = "imgui" %}
{% set version = "1.91.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/ocornut/{{ name }}/archive/v{{ version }}.tar.gz
    sha256: 6e62c87252e6b3725ba478a1c04dc604aa0aaeec78fedcf4011f1e52548f4cc9
  - path: CMakeLists.txt
  - path: imgui-config.cmake.in

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('imgui', max_pin='x.x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - cmake
    - ninja
    # x11 stuff
    - {{ cdt('mesa-libgl') }}        # [linux]
    - {{ cdt('mesa-libgl-devel') }}  # [unix and not arm64]
    - {{ cdt('mesa-dri-drivers') }}  # [unix and not arm64]
    - {{ cdt('libselinux') }}        # [linux]
    - {{ cdt('libxcb') }}            # [linux]
    - {{ cdt('libxdamage') }}        # [linux]
    - {{ cdt('libxfixes') }}         # [linux]
    - {{ cdt('libxxf86vm') }}        # [linux]
    - {{ cdt('libxext') }}           # [linux]
    - {{ cdt('libxau') }}            # [linux]
    - {{ cdt('expat-devel') }}       # [linux]
  host:
    - glfw
    - sdl2
  run:

test:
  files:
    - test/
  requires:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make  # [not win]
    - ninja  # [win]
  commands:
    - test -f $PREFIX/lib/libimgui${SHLIB_EXT}  # [unix]
    - if not exist %LIBRARY_PREFIX%\lib\imgui.lib exit 1  # [win]
    - if not exist %LIBRARY_PREFIX%\bin\imgui.dll exit 1  # [win]

about:
  home: https://github.com/ocornut/imgui
  summary: ImGui is a bloat-free graphical user interface library for C++. It outputs optimized vertex buffers that you can render anytime in your 3D-pipeline-enabled application.
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - Tobias-Fischer
    - traversaro
