context:
  name: imgui
  version: "1.91.8"
  build_number: 1
  docking: ${{ "true" if imgui_variant == "docking" else "false" }}

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  - if: docking == "true"
    then:
    - url: https://github.com/ocornut/${{ name }}/archive/v${{ version }}-docking.tar.gz
      sha256: 55f5e65abea635f2a8bfa9a92cd966448a363a262cf6dead7cc662fb0ab37612
    else:
    - url: https://github.com/ocornut/${{ name }}/archive/v${{ version }}.tar.gz
      sha256: db3a2e02bfd6c269adf0968950573053d002f40bdfb9ef2e4a90bce804b0f286
  - path: CMakeLists.txt
  - path: imgui-config.cmake.in

build:
  number: ${{ build_number }}
  variant:
    # down-prioritize the docking variant versus default
    down_prioritize_variant: ${{ 1 if imgui_variant == "docking" else 0 }}      
  string: ${{ "docking_" if imgui_variant == "docking" }}h${{ hash }}_${{ build_number }}

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
    - ${{ compiler('cxx') }}
    - cmake
    - ninja
  host:
    - if: linux
      then: libgl-devel
    - glfw
    - sdl2
    - libvulkan-loader
    - libvulkan-headers
  run_exports:
    - ${{ pin_subpackage('imgui', upper_bound='x.x.x') }}

tests:
  - package_contents:
      lib:
        - imgui
  - files:
      recipe:
        - test/
    requirements:
      run:
        - ${{ stdlib('c') }}
        - ${{ compiler('c') }}
        - ${{ compiler('cxx') }}
        - cmake
        - ninja
        - libvulkan-loader
        - libvulkan-headers
    script: run_test

about:
  summary: ImGui is a bloat-free graphical user interface library for C++. It outputs optimized vertex buffers that you can render anytime in your 3D-pipeline-enabled application.
  license: MIT
  license_file: LICENSE.txt
  homepage: https://github.com/ocornut/imgui

extra:
  recipe-maintainers:
    - Tobias-Fischer
    - traversaro
